name: autoclicker-detection
version: '${project.version}'
main: net.blazecraftserver.autoclickerdetection.Autoclicker_detection
api-version: '1.20'
commands:
  acd:
    description: Manage AutoclickerDetector settings
    usage: /<command>
permissions:
  autoclicker.admin:
    description: Allows access to AutoclickerDetector admin commands
    default: op